from __future__ import annotations

import ipaddress
from dataclasses import dataclass
from typing import Any


LOOPBACK_IPS = {"127.0.0.1", "::1"}
SERVICE_ACCOUNTS = {"svc_backup", "svc_monitor", "svc_splunkforwarder"}
SUPPRESSED_SOURCETYPES = {"perfmon", "syslog-heartbeat"}
ALERT_NAME_SUPPRESSION_TERMS = ("test", "debug", "heartbeat", "scheduled report")
KEEPALIVE_TERMS = ("keepalive", "ping")
RFC1918_NETWORKS = (
    ipaddress.ip_network("10.0.0.0/8"),
    ipaddress.ip_network("172.16.0.0/12"),
    ipaddress.ip_network("192.168.0.0/16"),
)


@dataclass(slots=True)
class SuppressionDecision:
    is_suppressed: bool
    reason: str | None = None


def evaluate_false_positive_rule(alert: dict[str, Any]) -> SuppressionDecision:
    alert_name = _normalized_text(alert.get("alert_name"))
    user = _normalized_text(alert.get("user"))
    src_ip = str(alert.get("src_ip") or "").strip()
    dest_ip = str(alert.get("dest_ip") or "").strip()
    sourcetype = _normalized_text(alert.get("sourcetype"))
    event_count = _safe_int(alert.get("event_count"))

    if src_ip in LOOPBACK_IPS:
        return SuppressionDecision(True, "Suppressed loopback traffic from a whitelisted source IP.")

    if user in SERVICE_ACCOUNTS:
        return SuppressionDecision(True, f"Suppressed routine activity generated by service account {user}.")

    if any(term in alert_name for term in ALERT_NAME_SUPPRESSION_TERMS):
        return SuppressionDecision(True, "Suppressed test or heartbeat style alert by name pattern.")

    if sourcetype in SUPPRESSED_SOURCETYPES:
        return SuppressionDecision(True, f"Suppressed known benign sourcetype {sourcetype}.")

    if event_count == 1 and "failed login" in alert_name:
        return SuppressionDecision(True, "Suppressed a single failed login with no repeat pattern.")

    no_user_present = not str(alert.get("user") or "").strip()
    if (
        _is_private_ip(src_ip)
        and _is_private_ip(dest_ip)
        and no_user_present
        and any(term in alert_name for term in KEEPALIVE_TERMS)
    ):
        return SuppressionDecision(True, "Suppressed internal keepalive or ping activity with no user context.")

    return SuppressionDecision(False, None)


def _normalized_text(value: Any) -> str:
    return str(value or "").strip().lower()


def _safe_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _is_private_ip(value: str) -> bool:
    try:
        address = ipaddress.ip_address(value)
    except ValueError:
        return False

    if address.version != 4:
        return False

    return any(address in network for network in RFC1918_NETWORKS)

